Repository IntelliSOFT-Consulting/corporate_services, pull requests merged in 2024-09, with the labels that each got.

#201 Timesheet file content string
  corporate_services/api/leave/update_annual_leave_allocations.py
  corporate_services/api/timesheet/timesheet_import.py
  corporate_services/fixtures/client_script.json
  corporate_services/fixtures/workflow.json
  corporate_services/hooks.py
  corporate_services/icl_corporate_services/custom/leave_application.json
Labels: enhancement, Resolved Issue

#196 fixing on the workflow and permissions of timesheet and leave applica…
  corporate_services/fixtures/client_script.json
  corporate_services/fixtures/workflow.json
  corporate_services/icl_corporate_services/custom/leave_application.json
Labels: enhancement

#198 customize asset custodianship form
  corporate_services/fixtures/print_format.json
  corporate_services/icl_corporate_services/custom/asset_custodianship_requisition.json
Labels: Resolved Issue

#203 Updating the timesheet doc to capture the link to timesheet submission
  corporate_services/api/timesheet/timesheet_fetch.py
  corporate_services/api/timesheet/timesheet_import.py
  corporate_services/icl_corporate_services/custom/timesheet.json
  corporate_services/icl_corporate_services/custom/timesheet_detail.json
Labels: ready for review, Resolved Issue

#205 Though Total hours are less than {} minimum hours.
  corporate_services/api/timesheet/timesheet_import.py
Labels: enhancement, Resolved Issue

#207 Work continuity plan customization
  corporate_services/api/timesheet/before_workflow_action.py
  corporate_services/hooks.py
  corporate_services/icl_corporate_services/custom/work_continuity_plan.json
Labels: bug, Try Fix

#206 Separation of email notification configuration
  corporate_services/api/timesheet/before_workflow_action.py
  corporate_services/hooks.py
Labels: enhancement, Resolved Issue, Try Fix

#208 timesheet import, double import
  corporate_services/fixtures/client_script.json
Labels: Resolved Issue

#210 Timesheet UI update import
  corporate_services/api/timesheet/timesheet_generation_export.py
  corporate_services/api/timesheet/timesheet_import.py
Labels: enhancement, Resolved Issue

#209 Update on the timesheet ui - adding background color on to it to iden…
  corporate_services/api/timesheet/timesheet_generation_export.py
Labels: Resolved Issue

#214 Hooks update notifications timesheet
  corporate_services/api/notification/asset_requisition.py
  corporate_services/api/notification/timesheet.py
  corporate_services/api/timesheet/before_workflow_action.py
  corporate_services/hooks.py
Labels: enhancement

#213 update of the hooks map methods
  corporate_services/api/notification/asset_requisition.py
  corporate_services/hooks.py
Labels: enhancement

#222 Workspaces update
  corporate_services/api/supplier/vat_calc.py
  corporate_services/fixtures/web_form.json
  corporate_services/fixtures/web_page.json
  corporate_services/fixtures/workspace.json
  corporate_services/icl_corporate_services/custom/asset_movement.json
  corporate_services/icl_corporate_services/custom/asset_movement_item.json
  corporate_services/icl_corporate_services/workspace/accounting/accounting.json
  corporate_services/icl_corporate_services/workspace/financial_reports/financial_reports.json
  corporate_services/icl_corporate_services/workspace/icl_finance/icl_finance.json
  corporate_services/icl_corporate_services/workspace/payables/payables.json
  corporate_services/icl_corporate_services/workspace/payroll/payroll.json
  corporate_services/icl_corporate_services/workspace/receivables/receivables.json
  corporate_services/icl_corporate_services/workspace/salary_payout/salary_payout.json
  corporate_services/icl_corporate_services/workspace/tax_&_benefits/tax_&_benefits.json
Labels: Try Fix

#221 Try fix for asset movement customizations
  corporate_services/api/supplier/vat_calc.py
  corporate_services/icl_corporate_services/custom/asset_movement.json
  corporate_services/icl_corporate_services/custom/asset_movement_item.json
Labels: bug, Try Fix

#226 Employee permission role manager update for finance
  corporate_services/api/role/get_role.py
  corporate_services/fixtures/client_script.json
  corporate_services/icl_corporate_services/custom/employee.json
Labels: enhancement, ready for review, Resolved Issue

#225 Employee permission role manager
  corporate_services/api/role/get_role.py
  corporate_services/fixtures/client_script.json
Labels: bug, enhancement

#223 update of the naming of contract terms under the employee list
  corporate_services/icl_corporate_services/doctype/contract_type/contract_type.json
Labels: Resolved Issue
